import * as FontAwesome5Icons from 'react-icons/fa';
import {
  TbCalendarCheck,
  TbCalendarPlus,
  TbPhone,
  TbPhoneCall,
  TbPhoneFilled,
  TbDeviceMobile,
  TbMail,
  TbMailFast,
  TbMapPin,
  TbMapPin2,
  TbMapPinFilled,
  TbMap,
  TbBuildingStore,
  TbBrandInstagram,
  TbBrandTiktok,
  TbBrandTiktokFilled,
  TbBrandX,
  TbBrandXFilled,
  TbBrandYoutube,
  TbBrandYoutubeFilled,
  TbBrandLinkedin,
  TbBrandChrome,
  TbBrandTumblr,
  TbWorld,
  TbWifi,
  TbThumbUp,
  TbMessage,
  TbCreditCard,
} from 'react-icons/tb';

export const FontIcon = {
  TbCalendarCheck,
  TbCalendarPlus,
  TbPhone,
  TbPhoneCall,
  TbPhoneFilled,
  TbDeviceMobile,
  TbMail,
  TbMailFast,
  TbMapPin,
  TbMapPin2,
  TbMapPinFilled,
  TbMap,
  TbBuildingStore,
  TbBrandInstagram,
  TbBrandTiktok,
  TbBrandTiktokFilled,
  TbBrandX,
  TbBrandXFilled,
  TbBrandYoutube,
  TbBrandYoutubeFilled,
  TbBrandLinkedin,
  TbBrandChrome,
  TbBrandTumblr,
  TbWorld,
  TbWifi,
  TbThumbUp,
  TbMessage,
  TbCreditCard,
  ...FontAwesome5Icons,
};

export const iconList = Object.values(FontIcon).map((icon) => icon.name);

export type IconType = keyof typeof FontIcon;
